name: Build

on:
  push:
    branches:
      - main
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            osname: Linux
          - os: windows-latest
            osname: Windows

    name: Build for ${{ matrix.osname }}
    permissions: write-all
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Build
        run: poetry build

      - name: Install PyInstaller
        run: poetry run pip install pyinstaller
     
      - name: Build
        run: poetry run pyinstaller -F --name NorthlightTools_${{ matrix.osname }} ./src/northlighttools/__init__.py
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release_${{ matrix.osname }}
          path: dist

      - name: Upload Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
            files: ./dist/NorthlightTools*
